spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: system
        uri: http://localhost:9200
        predicates:
        - Path=/system/**
      discovery:
        locator:
          enabled: true
# eureka config
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9100/eureka
server:
  port: 9101